# Travis-CI configuration file for Plinth

language: python
python:
  - "3.3"
  - "3.4"

# Debian packages required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gir1.2-packagekitglib-1.0

# Command to install dependencies
install:
  - pip install coverage==3.7
  - pip install "pgi>=0.0.10.1"
  - pip install -r requirements.txt

# Command to run tests
script: python3 setup.py test

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.oftc.net#freedombox"
    on_success: always
    on_failure: always
